name = "bitdog-api"
main = "src/index.ts"
compatibility_date = "2025-02-04"

[observability]
enabled = true

[vars]
API_TOKEN = "O-gEVZgCAtmon9TWakR0uVAjwO-hXxKC4DvtfbmB"
API_URL = "https://api.cloudflare.com/client/v4/accounts/e53fe9b1179261d74619b7241c0bdb8c/ai/run/@cf/meta/llama-3-8b-instruct"
