name = "bitdog-api"
main = "src/index.ts"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[vars]
API_URL = "https://api.cloudflare.com/client/v4/accounts/e53fe9b1179261d74619b7241c0bdb8c/ai/run/@cf/meta/llama-3-8b-instruct"
WHISPER_API_URL=" https://api.cloudflare.com/client/v4/accounts/e53fe9b1179261d74619b7241c0bdb8c/ai/run/@cf/openai/whisper"

